package com.tankpilot.obd.domain

enum class ObdConnectionState {
    DISCONNECTED,
    BLUETOOTH_UNAVAILABLE,
    PERMISSION_DENIED,
    SCANNING,
    PERIPHERAL_CONNECTING,
    PERIPHERAL_CONNECTED,
    DISCOVERING_SERVICES,
    RESOLVING_CHARACTERISTICS,
    ADAPTER_INITIALIZING,
    SEARCHING_FOR_PROTOCOL,
    VEHICLE_CONNECTED,
    ADAPTER_CONNECTED_VEHICLE_UNAVAILABLE,
    DISCONNECTING,
    ERROR
}
